---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - typescript
  tslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.ts"
exclude_paths:
- test/
